# Week 3 Assignment
* Download the "Week_3_Assignment.ipynb" notebook 
* Fill in the code in the cells marked with `# YOUR ANSWER HERE:` by answering the question/task defined in the cell above it starting with `GRADED:`
* Code cells outside of `# YOUR ANSWER HERE:` will not be considered for grading. 
  * Feel free to write outside of it for debugging
* Submit the updated notebook
  * Make sure to save your changes before submitting it!

In [14]:
# PLEASE, DO NOT MODIFY THIS CELL!

# IMPORT NECESSARY LIBRARIES AND DATA
import pandas as pd
import numpy as np

# SECtION A data
nparr = np.arange(145, 217).reshape(12, 6)

# data location
data_url = 'https://raw.githubusercontent.com/plotly/datasets/master/2011_february_us_airport_traffic.csv'
a_df = pd.read_csv(data_url, header=0)
a_df.head()


iata                            airport               city state country  \
0  ORD       Chicago O'Hare International            Chicago    IL     USA   
1  ATL  William B Hartsfield-Atlanta Intl            Atlanta    GA     USA   
2  DFW    Dallas-Fort Worth International  Dallas-Fort Worth    TX     USA   
3  PHX   Phoenix Sky Harbor International            Phoenix    AZ     USA   
4  DEN                        Denver Intl             Denver    CO     USA   

         lat        long    cnt  
0  41.979595  -87.904464  25129  
1  33.640444  -84.426944  21925  
2  32.895951  -97.037200  20662  
3  33.434167 -112.008056  17290  
4  39.858408 -104.667002  13781

## GRADED SECTION A

1. Determine the shape, number of dimensions and type of elements in the numpy array `nparr`
2. Determine the standard deviation of all elements in `nparr`
3. Determine the position (not the value) of the maximum value element in `nparr`
4. Create an array of the same shape as `nparr` but filled with zeros
5. Create an array of the same shape as `nparr` but filled with ones
6. Create an array of the same shape as `nparr` but where all elements are the square root values
7. Create an array result of shape `12` by `12` resulting from multiplication of nparr with transpose(`nparr`). Hint: use `np.dot`

In [15]:
# YOUR SECTION A ANSWER HERE (please use comments to number each of your answers)
# Assuming nparr is your numpy array and a_df is your DataFrame

# A1. Determine the shape, number of dimensions, and type of elements in nparr
shape = nparr.shape
dimensions = nparr.ndim
element_type = nparr.dtype

# A2. Determine the standard deviation of all elements in nparr
std_deviation = nparr.std()

# A3. Determine the position (not the value) of the maximum value element in nparr
max_position = np.unravel_index(nparr.argmax(), nparr.shape)

# A4. Create an array of the same shape as nparr but filled with zeros
zeros_array = np.zeros_like(nparr)

# A5. Create an array of the same shape as nparr but filled with ones
ones_array = np.ones_like(nparr)

# A6. Create an array of the same shape as nparr but where all elements are the square root values
sqrt_array = np.sqrt(nparr)

# A7. Create an array result of shape 12 by 12 resulting from multiplication of nparr with transpose(nparr)
result_array = np.dot(nparr, nparr.T)

# Print or use the results as needed
print("Shape:", shape)
print("Dimensions:", dimensions)
print("Element Type:", element_type)
print("Standard Deviation:", std_deviation)
print("Position of Maximum Value:", max_position)
print("Zeros Array:\n", zeros_array)
print("Ones Array:\n", ones_array)
print("Square Root Array:\n", sqrt_array)
print("Result Array:\n", result_array)

# Display the head of DataFrame a_df
print("\nDataFrame a_df:")
print(a_df.head())

Shape: (12, 6)
Dimensions: 2
Element Type: int64
Standard Deviation: 20.7826049057058
Position of Maximum Value: (11, 5)
Zeros Array:
 [[0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]]
Ones Array:
 [[1 1 1 1 1 1]
 [1 1 1 1 1 1]
 [1 1 1 1 1 1]
 [1 1 1 1 1 1]
 [1 1 1 1 1 1]
 [1 1 1 1 1 1]
 [1 1 1 1 1 1]
 [1 1 1 1 1 1]
 [1 1 1 1 1 1]
 [1 1 1 1 1 1]
 [1 1 1 1 1 1]
 [1 1 1 1 1 1]]
Square Root Array:
 [[12.04159458 12.08304597 12.12435565 12.16552506 12.20655562 12.24744871]
 [12.28820573 12.32882801 12.36931688 12.40967365 12.4498996  12.489996  ]
 [12.52996409 12.56980509 12.60952021 12.64911064 12.68857754 12.72792206]
 [12.76714533 12.80624847 12.84523258 12.88409873 12.92284798 12.9614814 ]
 [13.         13.03840481 13.07669683 13.11487705 13.15294644 13.19090596]
 [13.22875656 13.26649916 13.3041347  13.34166406 13.37908816 13.41640786]
 [13.45362405 13.490

## GRADED SECTION B

The dataframe `a_df` loads the dataset that contains information on a number of categories regarding traffic (variable `cnt` represents the actual traffic) at US airports from February 2011.
The dataset has already been loaded for you in the first code cell above.
 1. Print the number of rows for the subset of the dataframe for which traffic values are higher than `10,000` (ideally, you should format the print to put the thousands comma separator--as in `23,400` instead of `23400`
 2. Print the names of all the columns of the dataframe
 3. Print a subset of the dataframe containing the `10th` and the `3rd` rows of the original dataframe (`in that order`).
 4. Which US `state` has the `8th` largest __total__ airport traffic? Please, make sure you use the correct variable as described above.
 5. Which state has the second-most __total__ number of airports (i.e. the second-most amount of airports)?
 6. Of the cities that have multiple airports, which one has the least total traffic for all airports?
 7. What is the total airport traffic for all states that border the state of Massachusetts?


In [16]:
# YOUR SECTION B ANSWER HERE (please use comments to number each of your answers)

# B1: Print the number of rows for the subset of the dataframe for which traffic values are higher than 10,000
subset_high_traffic = a_df[a_df['cnt'] > 10000]
num_rows_high_traffic = subset_high_traffic.shape[0]
formatted_num_rows_high_traffic = f"{num_rows_high_traffic:,}"  # Format with thousands comma separator
print(f" B1: Number of rows with traffic > 10,000: {formatted_num_rows_high_traffic}")

# B2: Print the names of all the columns of the dataframe
all_columns = a_df.columns
print("\n B2: Names of all columns:")
print(all_columns)

# B3: Print a subset of the dataframe containing the 10th and the 3rd rows of the original dataframe
subset_10th_3rd_rows = a_df.iloc[[9, 2]]  # 10th and 3rd rows (using 0-based index)
print("\n B3: Subset of dataframe with 10th and 3rd rows:")
print(subset_10th_3rd_rows)

# B4: Which US state has the 8th largest total airport traffic?
state_8th_largest_traffic = a_df.groupby('state').sum().sort_values('cnt', ascending=False).index[7]
print("\n B4: State with the 8th largest total airport traffic:", state_8th_largest_traffic)

# B5: Which state has the second-most total number of airports?
state_second_most_airports = a_df['state'].value_counts().index[1]
print("\n B5: State with the second-most total number of airports:", state_second_most_airports)

# B6: Of the cities that have multiple airports, which one has the least total traffic for all airports?
city_least_traffic_multiple_airports = (
    a_df.groupby('city').agg({'cnt': 'sum', 'airport': 'count'})
    .loc[a_df['city'].value_counts()[a_df['city'].value_counts() > 1].index]
    .sort_values(by=['cnt', 'airport']).index[0]
)
print("\n B6: City with the least total traffic for all airports among cities with multiple airports:", city_least_traffic_multiple_airports)

# B7: What is the total airport traffic for all states that border the state of Massachusetts?
border_states_traffic = a_df[a_df['state'].isin(['VT', 'NH', 'RI', 'CT', 'NY'])]['cnt'].sum()
print("\n B7: Total airport traffic for all states that border Massachusetts:", border_states_traffic)


 B1: Number of rows with traffic > 10,000: 10

 B2: Names of all columns:
Index(['iata', 'airport', 'city', 'state', 'country', 'lat', 'long', 'cnt'], dtype='object')

 B3: Subset of dataframe with 10th and 3rd rows:
  iata                          airport               city state country  \
9  CLT  Charlotte/Douglas International          Charlotte    NC     USA   
2  DFW  Dallas-Fort Worth International  Dallas-Fort Worth    TX     USA   

         lat       long    cnt  
9  35.214011 -80.943126  10490  
2  32.895951 -97.037200  20662  

 B4: State with the 8th largest total airport traffic: CO

 B5: State with the second-most total number of airports: TX

 B6: City with the least total traffic for all airports among cities with multiple airports: Charleston

 B7: Total airport traffic for all states that border Massachusetts: 22007
